# Generated by Django 3.1.7 on 2022-06-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_name',
            field=models.CharField(default='post', max_length=100),
            preserve_default=False,
        ),
    ]
