# Generated by Django 3.1.7 on 2022-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_show_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='show_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
